name: Release

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [master]

jobs:
  on-success:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Echo 'hello release'
        run: echo 'hello release'
  on-failure:
    name: Notify
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Test failed
        run: echo 'The triggering workflow failed because of broken build/tests. Please check the logs and fix the issue.'
