name: Release

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [master]

jobs:
  on-success:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Echo 'hello releasee'
        run: echo 'hello release ${{ secrets.TEST_SECRET}} & ${{ secrets.TEST_VSCODE_ACTION}}'
  on-failure:
    name: Release failed
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Tests or build failed, release not triggered. Please check the logs and fix the issue
        run: |
          exit 1
