name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & Dependencies
        uses: ./.github/actions/node

      - name: Run tests
        run: |
          npm run test
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & Dependencies
        uses: ./.github/actions/node

      - name: Build project
        run: |
          npm run build
        env:
          CI: true
